### ISSUE TITLE
Display branch script

### ISSUE THREAD

**Issue by lizreal** [githubteacher/foundations-072115#80]
@patrickmckenna i forgot to ask, what script did you use to get your terminal to display the branch you are in?

**Comment by patrickmckenna** [comment]
@lizreal Sorry for the belated response. We'll be sending more info to you, but in the meantime here's one way to do it:

1. Write a script like [this](301e74f291d7271d48ea3aa3866a860f054f1ece), make it executable, and put it in your `PATH`.
1. In your `.bashrc` (or equivalent), include these lines:
```bash
# show current git branch in prompt
export PS1="\w\[\033[36m\]\$(print-git-branch.sh) \[\033[00m\] > "
```
